### ISSUE TITLE
A build triggered by the Finish Build Trigger doesn't trigger a notification

### ISSUE THREAD

**Issue by TheCrimsonSage** [pascal-zarrad/tc-discord-webhooks#25]
**Describe the bug**
A build triggered by the Finish Build Trigger doesn't trigger a notification. The original build that finished that was the trigger does make a notification though.

**To Reproduce**
1. Create a build config, let's call it build A. This build config is triggered by a VCS Trigger with branches specified that triggers it (ensure the branches are also in the Discord notify branch filter), e.g. +:refs/heads/release/QA
2. Create a build config, let's call it build B, that has a Finish Build Trigger on build A. This build gets the same VCS information from build A.
3. Create a change in the branch from step 1 and push it to trigger a new build

**Expected behavior**
Get a notification for build A and build B's start and stop events. Currently we only get notifications for build A and not B. Both A and B is the list of build configs that we want notifications for

**Screenshots**
Build A trigger config
<img width="960" alt="Screenshot 2021-07-15 at 11 43 34" src="https://user-images.githubusercontent.com/19888926/125790346-9ece3b87-787f-4202-b00f-d910d9985c6e.png">

Build B trigger config
<img width="1106" alt="Screenshot 2021-07-15 at 11 48 12" src="https://user-images.githubusercontent.com/19888926/125790395-79be4125-b258-4a88-8f7a-0fba7d99bd3a.png">

Discord notification config
<img width="925" alt="Screenshot 2021-07-15 at 11 48 40" src="https://user-images.githubusercontent.com/19888926/125790698-5e72ab97-fce3-4dcf-afaf-d27824f799e8.png">

**Additional context**
None

**Comment by pascal-zarrad** [comment]
Thank you for reporting that issue. I will check that issue and confirm if it is reproducible. If I can reproduce it, I will try to create a fix as soon as possible.

**Comment by TheCrimsonSage** [comment]
Thank you!

**Comment by pascal-zarrad** [comment]
I checked the issue and I'm unable to reproduce it.

**Used TeamCity version:** TeamCity Professional 2021.1.1 (build 92714)

It sounds like some configuration issue (maybe in your success trigger?).
Ensure that:
- Your success trigger is setup correctly and triggers a build at all.
- Depending on your TeamCity version and other configuration settings like VCS you might need to use logical branche names e.g. for the trigger in the format `+:release/QA` instead of `+:refs/heads/release/QA` if the build does not trigger at all.
- Ensure that the right branch is being build. The success trigger will always built the default branch specified in the VCS settings. See documentation [here](https://www.jetbrains.com/help/teamcity/2021.1/configuring-finish-build-trigger.html#Triggering+Settings).

Discord messages:
![image](https://user-images.githubusercontent.com/14060618/125857495-f1024192-ac00-4b76-8dbc-e5b113ad702c.png)

VCS Build Trigger:
![image](https://user-images.githubusercontent.com/14060618/125859038-e133e787-34d5-4f04-b71b-3ac4b080e736.png)

Success Trigger Build Trigger: 
![image](https://user-images.githubusercontent.com/14060618/125859274-7429eec8-db83-469d-8f07-4f36df51e11a.png)

**Comment by pascal-zarrad** [comment]
@TheCrimsonSage Any feedback if checking/adjusting your configuration fixed the issue?

**Comment by TheCrimsonSage** [comment]
Thank you for the suggestions, I've changed the builds to use logical branch names now:

<img width="433" alt="Screenshot 2021-07-21 at 07 50 05" src="https://user-images.githubusercontent.com/19888926/126437777-b76b7970-807e-4864-8caf-a759013957dc.png">

But although the Finish Build Trigger build actually fires with the correct branch filter which is not the default branch, I'm still not getting any notifications for when this build starts
<img width="1074" alt="Screenshot 2021-07-21 at 07 53 04" src="https://user-images.githubusercontent.com/19888926/126438080-58b75293-e9a8-4474-9eeb-502fb38f72aa.png">

I've even added notifications for all the branches in the settings
<img width="939" alt="Screenshot 2021-07-21 at 08 26 59" src="https://user-images.githubusercontent.com/19888926/126441593-7f6f92c5-ae2b-44a8-a1f3-947b38a9d9cc.png">

I can confirm if I start the build manually I get a notification
<img width="382" alt="Screenshot 2021-07-21 at 08 27 37" src="https://user-images.githubusercontent.com/19888926/126441679-4139c718-6099-4265-b2d8-d0ee1a87f9c7.png">

Is there anything else I can send you a screenshot of? I can't seem to replicate your success

**Comment by pascal-zarrad** [comment]
@TheCrimsonSage Can you check which branch your "Finish Build Trigger" is building in your build history? It should always build the default branch when triggered with this trigger, which means if your VCS default branch is set to something like master, main or develop the notification won't work as the trigger builds the wrong branch.

**Comment by pascal-zarrad** [comment]
Is there anything else I can send you a screenshot of?
 - Version Control Settings (Especially: Branch settings like default branch)
 - Some build in the history triggered by the Finish Build Trigger

**Comment by TheCrimsonSage** [comment]
Thank you! You helped me solve the issue 😄It turned out to be an issue with the branch not being properly set on the triggered build and it being the default branch. I had to setup a snapshot dependency to enforce the correct triggering of the branch. Thanks again for your patience!
